---
resources:
- name: ods-api-src
  type: git
  source:
    uri: https://github.com/markharrison17/OrgRefDataAPI.git

- name: python-test-src
  type: git
  source:
    uri: https://github.com/markharrison17/PythonTesting.git

- name: python-test-img
  type: docker-image
  source:
    repository: markharrison17/pythontest
    tag: '1.0'

jobs:
- name: build-python-test
  serial: true
  plan:
  - get: python-test-src
    trigger: true
  - put: python-test-img
    params:
      build: python-test-src

- name: test-and-build-odi-api
  serial: true
  plan:
  - aggregate:
    - get: python-test-img
      trigger: true
    - get: ods-api-src
      trigger: true
  - aggregate:
    - task: lint
      image: python-test-img
      file: ods-api-src/ci/pylint.yml
    # - task: unit
    #   image: python-test-img
    #   file: ods-api-src/ci/unit.yml
    # - task: coverage
    #   image: python-test-img
    #   file: ods-api-src/ci/coverage.yml
    # - task: context
    #   image: python-test-img
    #   file: ods-api-src/ci/context.yml
#  - put: aut-img
#    params:
#      build: context
