---
resources:
- name: ods-api-src
  type: git
  source:
    uri: https://github.com/markharrison17/OrgRefDataAPI.git

- name: python-test-src
  type: git
  source:
    uri: https://github.com/markharrison17/PythonTesting.git

- name: postgres-image-src
  type: git
  source:
    uri: https://github.com/markharrison17/OdsPostgresDbImg.git

- name: import-tool-src
  type: git
  source:
    uri: https://github.com/markharrison17/ImportTool.git

- name: python-test-img
  type: docker-image
  source:
    repository: markharrison17/pythontest
    tag: '1.0'
    username: {{docker-username}}
    password: {{docker-password}}

- name: ods-postgres-db-img
  type: docker-image
  source:
#    repository: markharrison17/ods-db-img
    repository: markharrison17/ods-import-img
    tag: '1.0'
    username: {{docker-username}}
    password: {{docker-password}}

jobs:
- name: build-python-test
  serial: true
  plan:
  - get: python-test-src
    trigger: true
  - put: python-test-img
    params:
      build: python-test-src

- name: build-ods-postgres-db-img
  serial: true
  plan:
  - get: postgres-image-src
    trigger: true
  - put: ods-postgres-db-img
    params:
      build: postgres-image-src

- name: test-and-build-ods-api
  serial: true
  plan:
  - aggregate:
    - get: python-test-img
      trigger: true
    - get: ods-api-src
      trigger: true
  - aggregate:
    - task: lint
      image: python-test-img
      file: ods-api-src/ci/pylint.yml
    - task: unit
      image: python-test-img
      file: ods-api-src/ci/unit.yml
    - task: coverage
      image: python-test-img
      file: ods-api-src/ci/coverage.yml
    - task: context
      image: python-test-img
      file: ods-api-src/ci/context.yml
#  - put: aut-img
#    params:
#      build: context

- name: test-and-build-import-tool
  serial: true
  plan:
  - aggregate:
    - get: ods-postgres-db-img
      trigger: true
    - get: import-tool-src
      trigger: true
  - aggregate:
    - task: lint
      image: ods-postgres-db-img
      file: import-tool-src/ci/pylint.yml
    - task: unit
      image: ods-postgres-db-img
      file: import-tool-src/ci/unit.yml
    - task: build
      image: ods-postgres-db-img
      file: import-tool-src/build.yml
    # - task: coverage
    #   image: python-test-img
    #   file: import-tool-src/ci/coverage.yml
    # - task: context
    #   image: python-test-img
    #   file: import-tool-src/ci/context.yml
